### ISSUE TITLE
Birthday date in calendar

### ISSUE THREAD

**Issue by yant0** [stephanritscher/Simple-Contacts#13]
I have never used any other contacts app beside the original simple contacts app but it would be great to have this feature. Personally, since i use other launcher, and that launcher have a dedicated widget for calendars but it only shows local & caldav. It would be great to be able to have the birthdays on a local calendar. Thx

**Comment by stephanritscher** [comment]
The proper solution for this is either in the calendar app or in the carddav/caldav provider, not in the contact app.
E.g. nextcloud/owncloud can be used as carddav/caldav provider which automatically creates a birthday calendar from the contacts' birthdays.
