### ISSUE TITLE
Merge with Fossify? 

### ISSUE THREAD

**Issue by alensiljak** [stephanritscher/Simple-Contacts#19]
Hi! Thank you for taking the initiative and adding the separate address fields. This was a constant mess over the years and different address books, and has now finally been resolved. 

I've just noticed that the Simple Mobile Tools now have an active fork and am wondering if you are aware of that. It would be great if your changes were merged there, to have all the improvements in one app. 

Their repo is here:
https://github.com/FossifyOrg/Contacts

Cheers

**Comment by DiagonalArg** [comment]
Yes.  I've been watching and waiting, and I'm wondering what "merge upstream changes" refers to in the latest release as Simple-Mobile-Tools was sold to some ad group.  Naveen, one of the dev's has taken over the continued FOSS version of the tools, appropriately named, "Fossify."  The first release of Fossify Contacts has been made (along with Calendar, Gallery, and File-manager; we are waiting on Notes, Music-Player, and Voice-Recorder).

**Comment by alensiljak** [comment]
That's good to know, thank you.

I'm not sure what you are referring to in regards to the latest release. I've only checked it today for the first time after a while.
The current version is 1.0.1 (https://github.com/FossifyOrg/Contacts/releases/tag/1.0.1) and the only change seems to be "Fix vcf importer (originally broke during view-binding migration)".
It does not seem that there are any significant updates from the MobileTools version. But it's a good start, nonetheless.

Hopefully things move forward differently from here on.

**Comment by alensiljak** [comment]
BTW, why don't you send him a pull request while there's still small number of changes and the probability of having merge conflicts is lower?

**Comment by DiagonalArg** [comment]
I should have said "first release."  Yes, I think as of now, he's just releasing the last version of Simple-Mobile that was FOSS.

> BTW, why don't you send him a pull request while there's still small number of changes and the probability of having merge conflicts is lower?

Great idea!
