### ISSUE TITLE
Choose what to share 

### ISSUE THREAD

**Issue by JokerGermany** [stephanritscher/Simple-Contacts#21]
### Feature description

On my Lenovo Tab the contact App let you choose which Details you like to share
<img alt="Screenshot_2024-02-18-00-44-04-025" src="https://github.com/FossifyOrg/Contacts/assets/30293477/3fe3d856-924b-4bc4-b5ea-bc10606fa2aa" width=240 />

### Why do you want this feature?

Only share the data which i want to share

### Additional information
Copy of https://github.com/FossifyOrg/Contacts/issues/82

**Comment by stephanritscher** [comment]
Nice idea / feature, but not in the scope I'm currently willing to contribute. It's great you already opened a request at Fossify since I'm trying to integrate my work there instead of maintaining a second fork.
