### ISSUE TITLE
Troubleshooting Simple Contacts for Suspected Issue

### ISSUE THREAD

**Issue by brianWreaves** [stephanritscher/Simple-Contacts#22]
Simple Contacts v6.22.7 Pro.
 
### Devices 

- Huawei Mate 9 running Android v9+
- macOS Sonoma v14.5
- VPS Linux AlmaLinux v8.10.0 STANDARD vzcontainer
 
### Apps

- cPanel's v120.0.10  
- Roundcube Webmail v1.6.6  
  - NOTE:  Preferences -> CardDAV -> “Use CATEGORIES instead of KIND=group (RFC6350) when creating new contact groups” is switched off
- Apple Contacts v16.0  
  - NOTE:  using vCard Format: “3.0” and Mac is setup with Language & Region as “Australia"
- DAVx5 v4.4.0.1-ose  
  - NOTE:  using CardDAV Contact group method -> "Groups are separate vCards"
 
### Issues
I’ve noticed 4 issues I suspect Simple Contacts, or perhaps DAVx5, is creating in Roundcube & Apple Contacts':
 
1. Something between the four apps is merging the address fields' from their individual fields into the “Street” field and renders everything horizontally but looks the same in Simple Contacts.  I can repair this in either Roundcube or Apple Contacts' and the corrected format will remain.
    A. **Apple**  
    Incorrect:  
    ![Apple Contact Address Incorrectly Formatted 01](https://github.com/stephanritscher/Simple-Contacts/assets/2764169/195a7a6c-79be-4d9c-a8aa-feb4cf63a641)
    Correct:  
    ![Apple Contact Address Correctly Formatted 01](https://github.com/stephanritscher/Simple-Contacts/assets/2764169/d317e59c-069c-4f4e-af18-efc67c9f7298)
    B. **Roundcube**  
    Incorrect:  
    ![Roundcube Contact Address Incorrectly Formatted 01](https://github.com/stephanritscher/Simple-Contacts/assets/2764169/e3ce2b1b-7f7d-4a42-97bc-a0db14676212)
    Correct:  
    ![Roundcube Contact Address Correctly Formatted 01](https://github.com/stephanritscher/Simple-Contacts/assets/2764169/835b85aa-b04e-4e5e-9e41-55154fb70976)
2. Given the lack of ability to select URL type  (e.g. Home, Work, etc.) in Simple Contacts, when a contact is sent via DAVx5 to the VPS it changes to “x-homepage” in Roundcube or Apple Contacts' regardless of its previous type.
    A.  **Apple**
    ![Apple Contact URL Incorrectly Labelled 01](https://github.com/stephanritscher/Simple-Contacts/assets/2764169/67479665-ac49-49b7-9831-3ba225abf8de)
    B.  **Roundcube**. 
    ![Roundcube Contact URL Incorrectly Labelled 01](https://github.com/stephanritscher/Simple-Contacts/assets/2764169/9e27841e-0a01-474d-8a20-892c5fc5889f)
    C.  **Simple**  
    ![Simple Contact URL No Label 01](https://github.com/stephanritscher/Simple-Contacts/assets/2764169/142f7f57-3f2f-4425-bbaf-ed4d5b796bac)
3. The order of the fields are not maintained in Simple Calendar from the order they are entered, regardless of the 3 interfaces in which they are entered.  As well, in all instanced the 2nd address should have the _Type_ of "Other" so something is causing it to change to "Address" in Apple Contacts, which you can see in the Apple images above.
   A.  **Correct**  
   [City], [State] [Post Code] 
   [Country] 
   
   is converted to 
   
   B.  **Incorrect**  
   
   [Post Code] [City] 
   [Country] [(State)]
    
   C.  **Simple**  
   ![Simple Calendar Address Incorrectly Formatted 01](https://github.com/stephanritscher/Simple-Contacts/assets/2764169/b652ebb2-feeb-4b0a-8543-997aec507063)
4. After viewing a contact in “Edit” mode and leaving the mode with the app’s Back arrow or using Android Back button, the contact is updated/re-sent to the VPS and Item # 1, # 2 & # 3 result.  I would think going back without clicking the tick icon ✓ would work like a “Cancel” and thus no changes.  That has been my experience with other apps with similar interactions.
 
If I do not sync my Android device, I’m not experiencing these issues.  How can I troubleshoot this further to determine the cause?  Please note, I am not a developer so I have limited skills.

**Comment by stephanritscher** [comment]
Disclaimer: Out of the apps you mention I only know/use DAVx5 and SimpleContacts.
@1: Do you use the fork I published on F-Droid or APK from Github? Do you have editing using the structured address field on (which is the default), i.e. do you have different controls for street, zip code, city etc. in Simple Contacts when editing? That's exactly what my fork should address. What you describe to me sounds a little bit like the original Simple Contacts app by SimpleMobileTools.
@2: Don't know.
@3: There is a display field in the contacts and SimpleContact has a fixed way to set this, maybe different from other apps. Currently there is no way to change this. For me, B looks correct and A looks incorrect, so I guess to make this right this would have to be configurable or depending on locale which is out of scope of my current interest.
@4: Sounds weird, but fixable, however not the top priority.

**Comment by brianWreaves** [comment]
> 1: Do you use the fork I published on F-Droid or APK from Github? 

Sorry, I may have wasted your time...  I intended to contact SimpleMobileTools, but was redirected here.  I'll see if I can reach him directly.

**Comment by stephanritscher** [comment]
Never mind. I recommend to also have a look at the open source forks at https://github.com/FossifyOrg.
