### ISSUE TITLE
automatic backup doesn't work

### ISSUE THREAD

**Issue by bingoxo** [stephanritscher/Simple-Contacts#23]
after enabling automatic backups nothing happens , i also can't choose an existing folder and have to create new one

**Comment by stephanritscher** [comment]
I never used that feature and don't know how it is supposed to work. Please address that point to the original author at https://simplemobiletools.com/ or the open source fork at https://github.com/FossifyOrg. I'm contributing the structured address feature to the latter project: https://github.com/FossifyOrg/Contacts/pull/57.
