### ISSUE TITLE
Refresh pull request for structured address to Fossify Contacts

### ISSUE THREAD

**Issue by bege10** [stephanritscher/Simple-Contacts#24]
The dev of Fossify Contacts asked you to refresh your pull request for structured address because of technical reasons.
https://github.com/FossifyOrg/Commons/pull/26
I'd love to see this app being regularly maintained in one place.
Thank you very much!

**Comment by stephanritscher** [comment]
Kindly refer to https://github.com/FossifyOrg/Commons/pull/32 and https://github.com/FossifyOrg/Contacts/pull/57
