### ISSUE TITLE
FR: optionally start search when opening app

### ISSUE THREAD

**Issue by j-lakeman** [stephanritscher/Simple-Contacts#25]
Awesome that you implemented separate address fields! Love it!
Would be nice if there was an option to activate the search field right upon opening the app. This would speed up the process of getting to a contact heaps IMHO.

**Comment by stephanritscher** [comment]
Try to report it at https://github.com/FossifyOrg/Contacts. I'm in the process of merging my changes there as well: https://github.com/FossifyOrg/Contacts/pull/57
