### ISSUE TITLE
Forced icon colour

### ISSUE THREAD

**Issue by filipkemuel** [stephanritscher/Simple-Contacts#3]
I can change the colour of the app-icon in the upstream version in the app-settings.

However it seems that the icon colour in this version has been "hardcoded". 
The option to change the colour is still there.. only it does nothing.

It would be nice if the setting acually worked..

**Comment by stephanritscher** [comment]
Hi @filipkemuel,
I didn't use this before so I didn't notice. I'll be looking into the issue - it might be related to renaming the package...
Best regards,
Stephan

**Comment by stephanritscher** [comment]
Hi @filipkemuel,
my theory was correct, but I was kind of blind due to (my) misleading wording.
I just published a release on Github with a correction - F-Droid will take a few days to catch up.
Best regards,
Stephan

**Comment by stephanritscher** [comment]
Please check version 6.22.3.1 which now is available in F-Droid - works for me :-D.
