### ISSUE TITLE
Pull request on original app

### ISSUE THREAD

**Issue by dwettstein** [stephanritscher/Simple-Contacts#6]
Hello

I appreciate your efforts and extended features of the original app. Have you considered contributing back to the origin via pull request? I'm afraid that your extended app will soon be outdated as it takes a lot of time to maintain an app and repository properly.

Additionally, your contribution would solve some issues and requested features on the original app:
- https://github.com/SimpleMobileTools/Simple-Contacts/issues/60
- https://github.com/SimpleMobileTools/Simple-Contacts/issues/364
- https://github.com/SimpleMobileTools/Simple-Contacts/issues/696
- https://github.com/SimpleMobileTools/Simple-Contacts/issues/678
- https://github.com/SimpleMobileTools/Simple-Contacts/issues/845

What do you think?

Best regards

**Comment by sphh** [comment]
@dwettstein: If you read the whole [thread](https://github.com/SimpleMobileTools/Simple-Contacts/issues/364) you would see that @stephanritscher already made a pull request https://github.com/SimpleMobileTools/Simple-Contacts/pull/156 to the original `Simple-Contacts` app, but @tibbi rejected it.

I am incredible grateful, that @stephanritscher forked and published his patched version. :bow: I do hope that @stephanritscher can keep up with his good work or that @tibbi finally sees the demand for structured address input and the value for us users and accepts the patch. :crossed_fingers:

**Comment by stephanritscher** [comment]
Yeah, as @sphh pointed out I'd prefer to contribute over maintaining a fork. And I still [try](https://github.com/SimpleMobileTools/Simple-Commons/pull/1664) where I think appropriate.

I cannot promise to maintain this fork very actively and actually that never was my goal, but as long as I use the app myself and upstream publishes updates, I will try to at least update this fork every few months or so.

Best regards

**Comment by dwettstein** [comment]
Oh, my bad, I'm sorry. I already thought it might be like that, but I couldn't find anything by searching through the issues and PRs. I even filtered by author. 😔  Sad that tibbi is not more open for contributions and is answering so harsh sometimes. 😢 
Nevertheless, the issues and your fork are linked now, so that people searching for your functionality should find your fork easier.

I'm glad that you are offering to maintain this fork. Thank you! 👍
