### ISSUE TITLE
Feature Question: Full Name handling

### ISSUE THREAD

**Issue by michaelof** [stephanritscher/Simple-Contacts#7]
Hi valued rebels,

as you encouragingly added the detailed address to Simple Contacts, I would ask if you maybe could add another RFC compliant feature Tibor doesn't want to add: Proper Handling of Full Name attribute.

I'm using SC with my selfhosted Nextcloud, synched with DAVx5, and whatever I set for Full Name in Nextcloud is overwritten my next change made and synched via NC.

I personally set my contact's Full Name to "Last Name, Titles etc. First Name", as I'm using these contacts via Bluetooth for my car, via my Fritzbox router to DECT-CATiq compliant phones etc. and of course a last name based search is the easiest.

Regards,
Michael

**Comment by stephanritscher** [comment]
Hi,

I'm into another project currently, but I might look into this at a later time.

Best regards,
Stephan

**Comment by stephanritscher** [comment]
Hi Michael,

please add your request to FossifyOrg fork. I also try to contribute my changes there: https://github.com/FossifyOrg/Contacts/pull/57

Best regards,
Stephan
